name: toggler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - zlib
  - pip:
      - altgraph
      - cellpose==3.1.1.2
      - fastremap
      - filelock
      - fill-voids
      - fsspec
      - imagecodecs
      - imageio
      - jinja2
      - joblib
      - lazy-loader
      - llvmlite
      - macholib
      - markupsafe
      - mpmath
      - natsort
      - networkx
      - numba
      - numpy
      - opencv-python-headless
      - packaging
      - pandas
      - pillow
      - pyinstaller
      - pyinstaller-hooks-contrib
      - pyqt6
      - pyqt6-qt6
      - pyqt6-sip
      - python-dateutil
      - pytz
      - roifile
      - scikit-image
      - scikit-learn
      - scipy
      - segment-anything
      - six
      - sympy
      - threadpoolctl
      - tifffile
      - torch
      - torchvision
      - tqdm
      - typing-extensions
      - tzdata
